// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocksController from "./locks_controller"
application.register("locks", LocksController)

/* import IconController from "./icon_controller"
application.register("icon", IconController)
 */
